services:
  backend:
    build: ./backend
    container_name: rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - D:/homy/S9/data-text-mining/Vectorestor:/app/Vectorestor
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: rag-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
